CFLAGS =
LIBS=

all:
	gcc -o envio_socket envio_socket.c $(CFLAGS) $(LIBS)
	gcc -o envio_socket_struct envio_socket_struct.c $(CFLAGS) $(LIBS)
	gcc -o recepcao_socket recepcao_socket.c $(CFLAGS) $(LIBS)

clean:
	rm -f envio_socket envio_socket_struct recepcao_socket
